// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {notification} from '../models';

export function GetGoogleEmails():Promise<Array<notification.Email>>;
